# Set the Docker Compose file format
version: '3.9'

# Define internal network
networks:
  internal:
    name: internal
    driver: bridge

# Define volumes
volumes:
  mariadb-storage:
    driver: local

# Define the services that make up the project
services:
  nestjs:
    build:
      context: .
      args:
        - APP_DEBUG=(true)
        - APP_ENV=local
    image: nest-demo:dev
    command: ["npm", "run", "start:dev"]
    depends_on:
      - mariadb
    volumes:
      - '.:/opt/nestjs'
    networks:
      - internal
    ports:
      - '8081:3000'

  mariadb:
    image: mariadb:latest
    environment:
      TZ: Asia/Ho_Chi_Minh
      MARIADB_DATABASE: 'nestjs_db'
      MARIADB_USER: 'nestjs_user'
      MARIADB_PASSWORD: 'password'
      MARIADB_ALLOW_EMPTY_ROOT_PASSWORD: 'yes'
    volumes:
      - 'mariadb-storage:/var/lib/mysql'
    networks:
      - internal
    healthcheck:
      test: [ 'CMD', 'mysqladmin', 'ping' ]
      retries: 3
      timeout: 5s
    ports:
      - '3308:3306'
